### PR TITLE
stable release: Truncate error message

### PR DESCRIPTION
**Pull request by thomasyu888**

### CODE REVIEW

**Comment by tschaffter** [comment]
@thomasyu888 There seems to be something wrong with this PR as it capture old commits that are already part of the default branch.

**Comment by thomasyu888** [comment]
@tschaffter I did a deletion of commits due to the configuration file that contained the MCW IP...

**Comment by tschaffter** [comment]
@thomasyu888 I don't understand this. You have not removed commits with this PR, you just added a single commit eb9dc025b08109a9c467ff0aac07e21e48baf923 to the default branch (squash and merge).

**Comment by thomasyu888** [comment]
@tschaffter please remind me to explain to you what happened next week on our one on one

**Pull request merged**
